# Generated by Django 5.1.5 on 2025-02-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinder', '0004_homework_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homework',
        ),
    ]
