# Generated by Django 5.1.5 on 2025-02-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinder', '0010_remove_event_student_remove_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
