# Generated by Django 5.1.5 on 2025-02-13 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinder', '0012_student_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kinder.student'),
        ),
    ]
