# Generated by Django 5.1.5 on 2025-02-13 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinder', '0013_event_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='student',
        ),
    ]
