# Generated by Django 5.1.5 on 2025-02-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinder', '0014_remove_event_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
