# Generated by Django 5.1.5 on 2025-02-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinder', '0016_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
