# Generated by Django 5.1.5 on 2025-02-18 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinder', '0017_activity_admin_comment_activity_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='activity_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
