# Generated by Django 5.1.5 on 2025-02-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinder', '0019_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
