# Generated by Django 5.1.5 on 2025-02-19 05:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinder', '0020_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='parent_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
