# Generated by Django 5.1.5 on 2025-02-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinder', '0022_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='parent_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
