# Generated by Django 5.1.5 on 2025-02-24 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinder', '0027_alter_staff_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
