# Generated by Django 5.1.5 on 2025-02-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinder', '0029_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='subjects_taught',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
