# Generated by Django 5.1.5 on 2025-02-25 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinder', '0030_staff_subjects_taught'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kinder.staff'),
        ),
    ]
