# Generated by Django 5.1.5 on 2025-02-26 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinder', '0032_attendance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
    ]
