# Generated by Django 5.1.5 on 2025-02-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinder', '0033_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
    ]
