# Generated by Django 5.1.5 on 2025-02-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinder', '0035_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='staff_profile_pics/'),
        ),
    ]
