# Generated by Django 5.1.5 on 2025-02-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinder', '0037_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='subjects_taught',
        ),
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
