# Generated by Django 5.1.5 on 2025-02-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinder', '0038_remove_staff_subjects_taught_staff_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
