# Generated by Django 5.1.6 on 2025-03-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinder', '0039_homework_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameProgressGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('game_attempts', models.JSONField(default=list)),
                ('best_rank', models.IntegerField(default=0)),
            ],
        ),
    ]
