# Generated by Django 5.1.6 on 2025-03-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinder', '0040_gameprogressgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChimpGameRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleGameRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
                ('time_taken', models.FloatField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='puzzle_images/')),
            ],
        ),
        migrations.CreateModel(
            name='XOGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_x', models.CharField(max_length=255)),
                ('player_o', models.CharField(max_length=255)),
                ('current_turn', models.CharField(default='X', max_length=1)),
                ('board_state', models.JSONField(default=list)),
                ('winner', models.CharField(blank=True, max_length=1, null=True)),
                ('toss_result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
