# Generated by Django 5.1.6 on 2025-03-05 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinder', '0041_chimpgamerecord_puzzlegamerecord_puzzleimage_xogame'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChimpGameRecord',
        ),
        migrations.DeleteModel(
            name='PuzzleGameRecord',
        ),
        migrations.DeleteModel(
            name='PuzzleImage',
        ),
        migrations.DeleteModel(
            name='XOGame',
        ),
        migrations.RenameField(
            model_name='gameprogressgroup',
            old_name='username',
            new_name='student_name',
        ),
    ]
