# Generated by Django 5.1.6 on 2025-03-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinder', '0043_puzzlegamerecord_puzzleimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChimpGameRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255, unique=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
