# Generated by Django 5.1.6 on 2025-03-13 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinder', '0045_xogame_xogamerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xogame',
            name='board_state',
        ),
    ]
