# Generated by Django 5.1.6 on 2025-03-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinder', '0047_xogame_board_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionGameRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255, unique=True)),
                ('user_input', models.CharField(max_length=10)),
                ('prediction', models.CharField(max_length=6)),
                ('second_input', models.CharField(max_length=5)),
                ('third_input', models.CharField(max_length=5)),
                ('fourth_input', models.CharField(max_length=5)),
                ('fifth_input', models.CharField(max_length=5)),
                ('result', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
