# Generated by Django 5.1.6 on 2025-03-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinder', '0049_alter_predictiongamerecord_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictiongamerecord',
            name='student_name',
            field=models.CharField(max_length=255),
        ),
    ]
